package tech.skullprogrammer.bguard.domain.enumeration;

public enum EAnomalyType {
    NEGATIVE_AMOUNT, INVALID_DATE_RANGE, PAYMENT_BEFORE_ISSUE_DATE, DUPLICATE_INVOICE, UNPAID_OVER_THRESHOLD, MISSING_SUPPLY_POINT, OVERLAPPING_BILLING_PERIOD
}
