name: billing-guard-app

services:
  bguard-app:
    # image: ${APP_IMAGE_NAME}
    build:
      context: ../../BE/bguard/.
      dockerfile: ../../BE/bguard/Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    environment:
      TECH_SKULLPROGRAMMER_DB_URL: bguard-db:5432
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      bguard-db:
        condition: service_healthy
    ports:
      - 8080:8080
  bguard-db:
    image: ${DB_IMAGE_NAME}
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      ALLOW_IP_RANGE: 0.0.0.0/0
    volumes:
      - ${DATA_DIR:-./data}:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always
  bguard-broker:
    image: apache/kafka:latest
    container_name: ${KAFKA_CONTAINER_NAME}
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://bguard-broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@bguard-broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - ${DATA_DIR:-./data}/kafka:/var/lib/kafka/data
    restart: always
