spring.application.name=app

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
tech.skullprogrammer.db.url=localhost:15432
tech.skullprogrammer.db.name=dbguard
spring.datasource.username=pguser
spring.datasource.password=pguser

spring.datasource.url=jdbc:postgresql://${tech.skullprogrammer.db.url}/${tech.skullprogrammer.db.name}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:db/test-data.sql

#Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.admin.fail-fast=true
spring.kafka.admin.operation-timeout=5s
spring.kafka.producer.acks=all
spring.kafka.producer.properties.delivery.timeout.ms=5s
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=tech.skullprogrammer.bguard.api.kafka.event
app.import.upload-dir=/Users/Shared/Work/bguard/imports     

jwt.expiration-ms=100000
jwt.secret=${JWT_SECRET:8KIodZIrYLu7JaFXnOmhecsSNX+NMbs6cLpr9feixgE=}