spring.application.name=app

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
tech.skullprogrammer.db.url=localhost:15432
tech.skullprogrammer.db.name=dbguard
spring.datasource.username=pguser
spring.datasource.password=pguser

spring.datasource.url=jdbc:postgresql://${tech.skullprogrammer.db.url}/${tech.skullprogrammer.db.name}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:db/test-data.sql