spring.application.name=app

# Abilita i log di debug per il controller che si trova nel modulo api
logging.level.tech.skullprogrammer.bguard.api.controller.CustomerController=debug
logging.pattern.console=%d{HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n
skullprogrammer.observability.mdc.key=correlationId

